# .streamlit/config.toml

[theme]
# The preset Streamlit theme to use as a base.
base="dark"

# Primary accent color for interactive elements.
primaryColor="#7792E3"

# Background color for the main content area.
backgroundColor="#0E1117"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#262730"

# Color of text.
textColor="#FAFAFA"

# Font family for all text in the app.
font="sans serif"